AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for FastAPI backend environment

Resources:
  FastAPIInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2
      SecurityGroups:
        - !Ref FastAPISecurityGroup
      Tags:
        - Key: Name
          Value: FastAPIBackend

  FastAPISecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  FastAPITargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: FastAPITargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId

Outputs:
  InstanceId:
    Description: The Instance ID of the FastAPI backend
    Value: !Ref FastAPIInstance
