name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: esclender # Replace when permissions to secrets is given lol
            password: Enero20.* # Replace when permissions to secrets is given lol

        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t esclender/doctums-back:latest 
        - name: push the docker image
          id: push-docker-image
          run: docker push esclender/doctums-back:latest