name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: AKIAXGMJMOP3HQ4SBH4V  #AKIAXGMJMOP3HCZOFNWN
            aws-secret-access-key: 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   #p5OwWrNxjo5SdGt9AmiPNRBWGu+uZVNJ3uEfK4Od
            aws-region: us-east-1

        - name: login to aws ecr
          id: login-aws
          run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 494746235894.dkr.ecr.us-east-1.amazonaws.com

        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t esclender/doctums-front:latest

        - name: tag image before push to ECR
          id: tag-docker-image
          run: docker tag esclender/doctums-front:latest 494746235894.dkr.ecr.us-east-1.amazonaws.com/esclender/doctums:latest
        
        - name: push the docker image
          id: push-docker-image
          run: docker push 494746235894.dkr.ecr.us-east-1.amazonaws.com/esclender/doctums:latest